apiVersion: v1
data:
  APP_NAME: api
  APP_VERSION: 1.0.0
kind: ConfigMap
metadata:
  labels:
    app: api
    tier: backend
  name: api-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    tier: backend
  name: api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: debug
    port: 10008
    targetPort: 10008
  selector:
    app: api
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
    tier: backend
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      tier: backend
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
      - args:
        - app.main:app
        - --host
        - 0.0.0.0
        - --port
        - "80"
        - --log-level
        - info
        - --workers
        - "1"
        command:
        - uvicorn
        envFrom:
        - configMapRef:
            name: api-config
        image: gcr.io/praxis-gear-314101/neutrino-api:71b3c45-dirty@sha256:8fd45aeb299c3dcf70c771b42f686565119fcae08138ec83192b5f98b57ef269
        name: api
        ports:
        - containerPort: 80
          name: http
        - containerPort: 10008
          name: debug
        resources:
          requests:
            cpu: 20m
            memory: 16Mi
